- hosts: web_nodes
  tasks:
    - name: "Install common dependencies"
      yum:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - "git"
        - "mc"
    - name: "Install python environment"
      yum:
        name: "{{ item }}"
        state: present
      become: yes
      with_items:
        - "python36"
        - "python36-pip"
    - name: "Install python dependencies"
      pip:
        name: "{{ item }}"
        executable: pip-3.6
      become: yes
      with_items:
        - "boto3"
        - "pytest"
        - "flask"
    - name: "Synchronize repository"
      git:
        repo: "https://github.com/luki6021/GIF_generator_uploading"
        dest: ~/animation-creator
    - name: "System variables"
      lineinfile:
        path: ~/.bashrc
        line: "{{ item }}"
      with_items:
        - "export PYTHONPATH={{ app_path }}"
        - "export APP_BUCKET_NAME={{ bucket_name }}"
        - "export QUEUE_NAME={{ queue_name }}"
    - name: "Set commit author"
      raw: "git config --global user.{{ item.key }} '{{ item.value }}'"
      with_items:
        - {key: "name", value: "{{ git_username }}"}
        - {key: "email", value: "{{ git_email }}"}
